<template>
    <div class="message-input">
      <div class="input-wrapper">
        <!-- 按回车键发送，输入框高度三行 -->
        <el-input
          v-model="message"
          :autosize="false"
          :rows="3"
          class="input"
          resize="none"
          type="textarea"
          @keydown="sendMessage_new"
        >
        </el-input>
        <div class="button-wrapper">
          <el-button 
        type="primary" 
        :class="{ 'jello-horizontal': isButtonClicked }"
        @click="sendMessage"
        @animationend="resetButtonState"
      >
            <el-icon class="el-icon--left">
              <Position />
            </el-icon>
            发送
          </el-button>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue';
  import { Position } from '@element-plus/icons-vue';
  
  const message = ref('');
  const emit = defineEmits(['send']);
  // 新增一个响应式变量来控制动画的触发
const isButtonClicked = ref(false);
 //使用shift+enter换行
const sendMessage_new = (e) => {
  if (e.keyCode === 13 && e.shiftKey) {
    e.preventDefault(); // 阻止默认行为
    message.value += '\n';
  } else if (e.keyCode === 13) {
    e.preventDefault(); // 阻止默认行为
    sendMessage();
  }
}

  const sendMessage = () => {
    if (message.value.trim()) {
      emit('send', message.value);
      message.value = '';
      // 设置按钮状态为已点击，触发动画
      isButtonClicked.value = true;
    }
  };

  const resetButtonState = () => {
  // 动画结束后重置按钮状态
  isButtonClicked.value = false;
};
  </script>
  
  <style lang="scss" scoped>
  .message-input {
    padding: 15px;
    border-top: 1px solid rgba(black, 0.07);
    border-left: 1px solid rgba(black, 0.07);
    border-right: 1px solid rgba(black, 0.07);
    border: 1px solid rgba(black, 0.07);
    border-top-right-radius: 5px;
    border-top-left-radius: 5px;
    border-radius:20px;
  }
  .input-wrapper {
  flex-grow: 1; /* 使输入框占据多余空间 */
  display: flex;
  align-items: center; /* 垂直居中输入框和按钮 */

  .input {
    flex-grow: 1; /* 使输入框占据多余空间 */
    margin-right: 10px; /* 为按钮留出间隔 */
  }
}
  .button-wrapper {
    margin-top: 0; /* 在同一行上时不需要顶部间距 */
    display: flex;
    justify-content: flex-end;
    margin-top: 20px;
  }

  .jello-horizontal {
	-webkit-animation: jello-horizontal 0.9s both;
	        animation: jello-horizontal 0.9s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-6-28 14:9:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
 @-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
            transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
            transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}

  </style>
  