<template>
  <div class="bg-pan-right">
    <!-- 菜单置于顶部 -->
    <div class="top-menu">
      <el-menu default-active="1" mode="horizontal" class="el-menu-horizontal" @select="handleSelect">
        <el-menu-item index="1">对话</el-menu-item>
        <el-menu-item index="2">图片识别</el-menu-item>
        <el-menu-item index="3">机器翻译</el-menu-item>
        <el-menu-item index="4">语音测评</el-menu-item>
        <li v-if = "user.permission == 100">
           <el-menu-item index="5">通讯录</el-menu-item>
        </li>
      </el-menu>
    </div>
    <div class="panel" :class="{ 'scale-out-horizontal': isAnimationActive }">
    <RouterView/>
    </div>
  </div>
</template>


<script setup>
import { ref , onMounted} from 'vue';
import { useRouter } from 'vue-router';
import {useTestStore} from '@/store/user' // 确保正确导入user

// 用户信息
const user = useTestStore()
const router = useRouter();
const isAnimationActive = ref(false);

// 菜单选项点击事件
const handleSelect = (index) => {
  switch (index) {
    case '1':
      triggerAnimationAndNavigate('/home/Chat');
      break;
    case '2':
      triggerAnimationAndNavigate('/home/recognition');
      break;
    case '3':
      triggerAnimationAndNavigate('/home/translation');
      break;
    case '4':
      triggerAnimationAndNavigate('/home/evaluation');
      break;
    case '5':
      triggerAnimationAndNavigate('/home/contacts');
      break;
    default:
      // 默认行为
      break;
  }
};

// 触发动画并等待动画结束后导航
const triggerAnimationAndNavigate = (path) => {
  // 假设isAnimationActive是一个Vue的响应式引用
  isAnimationActive.value = true;

  // 监听动画结束事件
  const onAnimationEnd = () => {
    // 移除事件监听器
    const panel = document.querySelector('.panel');
    panel.removeEventListener('animationend', onAnimationEnd);

    // 执行路由跳转
    router.push({ path: path });

    // 重置动画标志位
    isAnimationActive.value = false;
  };

  // 添加事件监听器
  const panel = document.querySelector('.panel');
  panel.addEventListener('animationend', onAnimationEnd);
};

</script>

<style scoped>

/* 新增的顶部菜单样式 */

.home-view {
  width: 100vw;
  /* display: flex; */
  justify-content: center;
  height: 100vh;
  overflow: hidden;
  background-image: url(https://bu.dusays.com/2023/12/12/6577c98beafc0.webp);
}
.bg-pan-right {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: hidden;
  top: 0;
  left: 0;
  background-image: linear-gradient(270deg, #cc6aa5, #3e91cc, #2dcca7);
  background-size: 600% 100%;
	-webkit-animation: bg-pan-right 8s infinite;
	        animation: bg-pan-right 8s infinite;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-6-28 13:47:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bg-pan-right
 * ----------------------------------------
 */
 @-webkit-keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}
@keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}

.panel.scale-out-horizontal {
  -webkit-animation: scale-out-horizontal 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: scale-out-horizontal 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-6-28 16:42:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-horizontal
 * ----------------------------------------
 */
 @-webkit-keyframes scale-out-horizontal {
  0% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(0);
            transform: scaleX(0);
    opacity: 1;
  }
}
@keyframes scale-out-horizontal {
  0% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(0);
            transform: scaleX(0);
    opacity: 1;
  }
}




</style>
